'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Automatische My.Settings-Speicherfunktion"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button1_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button1_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button1_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button1_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button1_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button1_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button1_Link() As String
            Get
                Return CType(Me("Button1_Link"),String)
            End Get
            Set
                Me("Button1_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button1_Text() As String
            Get
                Return CType(Me("Button1_Text"),String)
            End Get
            Set
                Me("Button1_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button2_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button2_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button2_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button2_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button2_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button2_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button2_Link() As String
            Get
                Return CType(Me("Button2_Link"),String)
            End Get
            Set
                Me("Button2_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button2_Text() As String
            Get
                Return CType(Me("Button2_Text"),String)
            End Get
            Set
                Me("Button2_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button3_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button3_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button3_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button3_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button3_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button3_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button3_Link() As String
            Get
                Return CType(Me("Button3_Link"),String)
            End Get
            Set
                Me("Button3_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button3_Text() As String
            Get
                Return CType(Me("Button3_Text"),String)
            End Get
            Set
                Me("Button3_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button4_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button4_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button4_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button4_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button4_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button4_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button4_Link() As String
            Get
                Return CType(Me("Button4_Link"),String)
            End Get
            Set
                Me("Button4_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button4_Text() As String
            Get
                Return CType(Me("Button4_Text"),String)
            End Get
            Set
                Me("Button4_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button5_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button5_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button5_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button5_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button5_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button5_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button5_Link() As String
            Get
                Return CType(Me("Button5_Link"),String)
            End Get
            Set
                Me("Button5_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button5_Text() As String
            Get
                Return CType(Me("Button5_Text"),String)
            End Get
            Set
                Me("Button5_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button6_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button6_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button6_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button6_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button6_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button6_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button6_Link() As String
            Get
                Return CType(Me("Button6_Link"),String)
            End Get
            Set
                Me("Button6_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button6_Text() As String
            Get
                Return CType(Me("Button6_Text"),String)
            End Get
            Set
                Me("Button6_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button7_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button7_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button7_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button7_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button7_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button7_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button7_Link() As String
            Get
                Return CType(Me("Button7_Link"),String)
            End Get
            Set
                Me("Button7_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button7_Text() As String
            Get
                Return CType(Me("Button7_Text"),String)
            End Get
            Set
                Me("Button7_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button8_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button8_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button8_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button8_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button8_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button8_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button8_Link() As String
            Get
                Return CType(Me("Button8_Link"),String)
            End Get
            Set
                Me("Button8_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button8_Text() As String
            Get
                Return CType(Me("Button8_Text"),String)
            End Get
            Set
                Me("Button8_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button9_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button9_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button9_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button9_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button9_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button9_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button9_Link() As String
            Get
                Return CType(Me("Button9_Link"),String)
            End Get
            Set
                Me("Button9_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button9_Text() As String
            Get
                Return CType(Me("Button9_Text"),String)
            End Get
            Set
                Me("Button9_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button10_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button10_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button10_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button10_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button10_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button10_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button10_Link() As String
            Get
                Return CType(Me("Button10_Link"),String)
            End Get
            Set
                Me("Button10_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button10_Text() As String
            Get
                Return CType(Me("Button10_Text"),String)
            End Get
            Set
                Me("Button10_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button11_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button11_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button11_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button11_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button11_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button11_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button11_Link() As String
            Get
                Return CType(Me("Button11_Link"),String)
            End Get
            Set
                Me("Button11_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button11_Text() As String
            Get
                Return CType(Me("Button11_Text"),String)
            End Get
            Set
                Me("Button11_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button12_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button12_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button12_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button12_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button12_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button12_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button12_Link() As String
            Get
                Return CType(Me("Button12_Link"),String)
            End Get
            Set
                Me("Button12_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button12_Text() As String
            Get
                Return CType(Me("Button12_Text"),String)
            End Get
            Set
                Me("Button12_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button13_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button13_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button13_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button13_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button13_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button13_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button13_Link() As String
            Get
                Return CType(Me("Button13_Link"),String)
            End Get
            Set
                Me("Button13_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button13_Text() As String
            Get
                Return CType(Me("Button13_Text"),String)
            End Get
            Set
                Me("Button13_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button14_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button14_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button14_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button14_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button14_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button14_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button14_Link() As String
            Get
                Return CType(Me("Button14_Link"),String)
            End Get
            Set
                Me("Button14_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button14_Text() As String
            Get
                Return CType(Me("Button14_Text"),String)
            End Get
            Set
                Me("Button14_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button15_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button15_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button15_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button15_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button15_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button15_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button15_Link() As String
            Get
                Return CType(Me("Button15_Link"),String)
            End Get
            Set
                Me("Button15_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button15_Text() As String
            Get
                Return CType(Me("Button15_Text"),String)
            End Get
            Set
                Me("Button15_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button16_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button16_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button16_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button16_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button16_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button16_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button16_Link() As String
            Get
                Return CType(Me("Button16_Link"),String)
            End Get
            Set
                Me("Button16_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button16_Text() As String
            Get
                Return CType(Me("Button16_Text"),String)
            End Get
            Set
                Me("Button16_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button17_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button17_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button17_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button17_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button17_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button17_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button17_Link() As String
            Get
                Return CType(Me("Button17_Link"),String)
            End Get
            Set
                Me("Button17_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button17_Text() As String
            Get
                Return CType(Me("Button17_Text"),String)
            End Get
            Set
                Me("Button17_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button18_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button18_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button18_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button18_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button18_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button18_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button18_Link() As String
            Get
                Return CType(Me("Button18_Link"),String)
            End Get
            Set
                Me("Button18_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button18_Text() As String
            Get
                Return CType(Me("Button18_Text"),String)
            End Get
            Set
                Me("Button18_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button19_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button19_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button19_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button19_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button19_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button19_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button19_Link() As String
            Get
                Return CType(Me("Button19_Link"),String)
            End Get
            Set
                Me("Button19_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button19_Text() As String
            Get
                Return CType(Me("Button19_Text"),String)
            End Get
            Set
                Me("Button19_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button20_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button20_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button20_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button20_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button20_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button20_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button20_Link() As String
            Get
                Return CType(Me("Button20_Link"),String)
            End Get
            Set
                Me("Button20_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button20_Text() As String
            Get
                Return CType(Me("Button20_Text"),String)
            End Get
            Set
                Me("Button20_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button21_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button21_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button21_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button21_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button21_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button21_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button21_Text() As String
            Get
                Return CType(Me("Button21_Text"),String)
            End Get
            Set
                Me("Button21_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button22_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button22_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button22_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button22_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button22_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button22_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button22_Link() As String
            Get
                Return CType(Me("Button22_Link"),String)
            End Get
            Set
                Me("Button22_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button22_Text() As String
            Get
                Return CType(Me("Button22_Text"),String)
            End Get
            Set
                Me("Button22_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button23_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button23_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button23_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button23_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button23_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button23_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button23_Link() As String
            Get
                Return CType(Me("Button23_Link"),String)
            End Get
            Set
                Me("Button23_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button23_Text() As String
            Get
                Return CType(Me("Button23_Text"),String)
            End Get
            Set
                Me("Button23_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button21_Link() As String
            Get
                Return CType(Me("Button21_Link"),String)
            End Get
            Set
                Me("Button21_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button24_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button24_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button24_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button24_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button24_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button24_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button24_Link() As String
            Get
                Return CType(Me("Button24_Link"),String)
            End Get
            Set
                Me("Button24_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button24_Text() As String
            Get
                Return CType(Me("Button24_Text"),String)
            End Get
            Set
                Me("Button24_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button25_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button25_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button25_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button25_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button25_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button25_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button25_Link() As String
            Get
                Return CType(Me("Button25_Link"),String)
            End Get
            Set
                Me("Button25_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button25_Text() As String
            Get
                Return CType(Me("Button25_Text"),String)
            End Get
            Set
                Me("Button25_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button26_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button26_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button26_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button26_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button26_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button26_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button26_Link() As String
            Get
                Return CType(Me("Button26_Link"),String)
            End Get
            Set
                Me("Button26_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button26_Text() As String
            Get
                Return CType(Me("Button26_Text"),String)
            End Get
            Set
                Me("Button26_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button27_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button27_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button27_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button27_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button27_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button27_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button27_Link() As String
            Get
                Return CType(Me("Button27_Link"),String)
            End Get
            Set
                Me("Button27_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button27_Text() As String
            Get
                Return CType(Me("Button27_Text"),String)
            End Get
            Set
                Me("Button27_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button28_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button28_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button28_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button28_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button28_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button28_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button28_Link() As String
            Get
                Return CType(Me("Button28_Link"),String)
            End Get
            Set
                Me("Button28_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button28_Text() As String
            Get
                Return CType(Me("Button28_Text"),String)
            End Get
            Set
                Me("Button28_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button29_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button29_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button29_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button29_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button29_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button29_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button29_Link() As String
            Get
                Return CType(Me("Button29_Link"),String)
            End Get
            Set
                Me("Button29_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button29_Text() As String
            Get
                Return CType(Me("Button29_Text"),String)
            End Get
            Set
                Me("Button29_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button30_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button30_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button30_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button30_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button30_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button30_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button30_Link() As String
            Get
                Return CType(Me("Button30_Link"),String)
            End Get
            Set
                Me("Button30_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button30_Text() As String
            Get
                Return CType(Me("Button30_Text"),String)
            End Get
            Set
                Me("Button30_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button31_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button31_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button31_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button31_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button31_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button31_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button31_Link() As String
            Get
                Return CType(Me("Button31_Link"),String)
            End Get
            Set
                Me("Button31_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button31_Text() As String
            Get
                Return CType(Me("Button31_Text"),String)
            End Get
            Set
                Me("Button31_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button32_Hintergrundfarbe() As String
            Get
                Return CType(Me("Button32_Hintergrundfarbe"),String)
            End Get
            Set
                Me("Button32_Hintergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button32_Vordergrundfarbe() As String
            Get
                Return CType(Me("Button32_Vordergrundfarbe"),String)
            End Get
            Set
                Me("Button32_Vordergrundfarbe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button32_Link() As String
            Get
                Return CType(Me("Button32_Link"),String)
            End Get
            Set
                Me("Button32_Link") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Button32_Text() As String
            Get
                Return CType(Me("Button32_Text"),String)
            End Get
            Set
                Me("Button32_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Einstellungen_DarkLightmode() As String
            Get
                Return CType(Me("Einstellungen_DarkLightmode"),String)
            End Get
            Set
                Me("Einstellungen_DarkLightmode") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.easy_bookmark.My.MySettings
            Get
                Return Global.easy_bookmark.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
